machine:
    #pre:
    #    - curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
    os: linux
    services:
        - docker

dependencies:
    override:
        - sudo pip install -U docker-compose
        
language: python

test:
    override:
        - docker-compose up --build